import type { Metadata } from 'next';
import { Didact_Gothic, Geist } from 'next/font/google';
import './globals.css';

import { Navbar } from '@/components/layout/navbar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const didactGothic = Didact_Gothic({
  variable: '--font-didact-gothic',
  subsets: ['latin'],
  weight: ['400'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${didactGothic.className} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
