import type { Metadata } from "next";
import "./globals.css";

import { didactGothic, helvetica } from "@/assets/fonts";
import { Navbar } from "@/components/layout/navbar";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={cn("scroll-smooth")} lang="en">
      <body className={`${helvetica.variable} ${didactGothic.className} antialiased`}>
        <Navbar />
        <div className="fixed top-0 h-[calc(3.875rem-1px)] w-full bg-sky-100" />
        {children}
      </body>
    </html>
  );
}
